= Logo Art - My Logo Palace
:toc: macro
:toclevels: 3
Sun Qian <fredsuvn@163.com>
:emaill: fredsuvn@163.com
:url: https://github.com/fredsuvn/logo-art
:me-url: https://github.com/fredsuvn
:qq: QQ: 2510701977
:license: https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license]

*Hi there, welcome to my logo palace!*

*This is an amazing place collects a lot of genius logos designed by a genius logo designer -- ME!*

toc::[]

== My Logos and Their History

=== Suvn

image:src/suvn/1-hive/suvn.svg[,64]

=== SrcLab

image:src/srclab/srclab/1/srclab-2.svg[,64]
image:src/srclab/srclab/2/srclab.svg[,64]
image:src/srclab/srclab/3/srclab-2.svg[,64]
image:src/srclab/srclab/4/srclab-4.svg[,64]
image:src/srclab/srclab/5-hive/srclab-2.svg[,64]

==== Boat

* `boat`:
image:src/srclab/boat/1/boat.svg[,64]
image:src/srclab/boat/2/boat.svg[,64]
image:src/srclab/boat/3/boat.svg[,64]
image:src/srclab/boat/4-hive/boat.svg[,64]
image:src/srclab/boat/5-boat/boat.svg[,64]

* `boat-spring-boot`:
image:src/srclab/boat/1/boat-spring-boot.svg[,64]
image:src/srclab/boat/2/boat-spring-boot.svg[,64]
image:src/srclab/boat/3/boat-spring-boot.svg[,64]
image:src/srclab/boat/4-hive/boat-spring-boot.svg[,64]
image:src/srclab/boat/5-boat/boat-spring-boot.svg[,64]

* `grpc-spring-boot`:
image:src/srclab/boat/3/grpc-spring-boot.svg[,64]
image:src/srclab/boat/4-hive/grpc-spring-boot.svg[,64]
image:src/srclab/boat/5-boat/grpc-spring-boot.svg[,64]

==== Home

* `home-light`:
image:src/srclab/home/1-hive/firefly.svg[,64]
image:src/srclab/home/2-home/home-light.svg[,64]

* `home-port`:
image:src/srclab/home/1-hive/homeport.svg[,64]
image:src/srclab/home/2-home/home-port.svg[,64]

* `home-ship`:
image:src/srclab/home/2-home/home-ship.svg[,64]

=== Xhome

image:src/xhome/alpha/xteam/4.1/xteam-home.svg[,64]
image:src/xhome/alpha/xteam/4.2/xtea-home.svg[,64]
image:src/xhome/xhome.svg[,64]

==== Xtea

* `xtea`:
image:src/xhome/alpha/xtea/1/xtea.svg[,64]
image:src/xhome/alpha/xtea/2/xtea.svg[,64]
image:src/xhome/alpha/xtea/3/xtea.svg[,64]
image:src/xhome/alpha/xtea/4/xtea.svg[,64]
image:src/xhome/xtea.svg[,64]

* `xtea-spring-boot`:
image:src/xhome/alpha/xtea/1/xtea-spring-boot.svg[,64]
image:src/xhome/alpha/xtea/2/xtea-spring-boot.svg[,64]
image:src/xhome/alpha/xtea/3/xtea-spring-boot.svg[,64]
image:src/xhome/alpha/xtea/4/xtea-spring-boot.svg[,64]
image:src/xhome/xtea-spring-boot.svg[,64]

* `grpc-spring-boot`:
image:src/xhome/alpha/xtea/4/grpc-spring-boot.svg[,64]
image:src/xhome/grpc-spring-boot.svg[,64]

=== Some Others

* `sonluo`:
image:src/sonluo/1-hive/sonluo.svg[,64]

* `tousie`:
image:src/tousie/1-hive/tousie.svg[,64]

* `ufotv`:
image:src/ufotv/1-hive/ufotv.svg[,64]

=== More in link:src[Here]!

== About Me

* {emaill}
* {me-url}
* {qq}
* {url}

== License

{license}